apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: brew-line-lager
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: default
  path: ./clusters/copenhagen-lyngby/sets/brew-line-lager
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: copenhagen-lyngby-infra
