apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: brew-line-porter
  namespace: flux-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: flux-workspace
  path: ./clusters/copenhagen-lyngby/sets/brew-line-porter
  prune: true
  decryption:
    provider: sops
  dependsOn:
  - name: copenhagen-lyngby-infra
