apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: copenhagen-lyngby-infra
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: default
  path: ./clusters/copenhagen-lyngby/infra
  prune: true
  wait: true
  timeout: 10m
