apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: coffee-line-dorothy
  namespace: flux-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: flux-workspace
  path: ./clusters/portland/sets/coffee-line-dorothy
  prune: true
  decryption:
    provider: sops
  dependsOn:
  - name: portland-infra
