apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: coffee-line-dorothy
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: default
  path: ./clusters/portland/sets/coffee-line-dorothy
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: portland-infra
