apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: portland-infra
  namespace: flux-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: flux-workspace
  path: ./clusters/portland/infra
  prune: true
  decryption:
    provider: sops
