apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: line2
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: default
  path: ./clusters/e2e-test-site/sets/line2
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: e2e-test-site-infra
