resources:
- ../base
- ./../../../../../../apps/dummy-app/1.0
namespace: dummy-app
configMapGenerator:
- name: ip-addresses.config.json
  behavior: replace
  files:
  - configuration-ipaddresses
- name: configuration-ipaddresses
  behavior: replace
  files:
  - ip-addresses.config.json
  - ip-addresses.config2.json
